### PR TITLE
Added feature for generating the parameters file

### PR DESCRIPTION
**Pull request by jkiddo**
@jawalonoski something along these lines correct? (in relation to https://chat.fhir.org/#narrow/stream/179166-implementers/topic/From.20Synthea.20Bulk.20Export.20to.20Bulk.20Import)

### CODE REVIEW

**Comment by jawalonoski** [comment]
Questions:

1. Does the order of the entries in the parameters file matter? For example, loading dependencies in order: `Organization`,`Location`,`Practitioner`,`PractitionerRole`, etc. If so, then this needs alteration. If not, good to go.

2. If you want `http://localhost:8000/` to be configurable, you could add another field to `synthea.properties`.

Comment:

1. This change introduces a few Checkstyle warnings:

```
Exporter.java:505:5: '{' at column 5 should be on the previous line. [LeftCurly]
Exporter.java:508: Line is longer than 100 characters (found 101). [LineLength]
Exporter.java:521:82: WhitespaceAround: '+' is not preceded with whitespace. [WhitespaceAround
Exporter.java:521:83: WhitespaceAround: '+' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
Exporter.java:523: Line is longer than 100 characters (found 113). [LineLength]
```

**Comment by jkiddo** [comment]
@jawalonoski apparently the checkstyle config file in the repo is not working with the https://plugins.jetbrains.com/plugin/1065-checkstyle-idea plugin, so I'm a bit in the dark. I _think_ I adressed all your findings.

**Comment by jawalonoski** [comment]
Sorry for the delay. Looking at it now.

**Review by jawalonoski — APPROVED** [review]

**Comment by jawalonoski** [comment]
There were minor check style complaints, but I'll fix them post-merge.

Thank you for the pull request!

**Pull request merged**
