### PR TITLE
Implementation of Chronic Meds Renewal (#564)

### PR DESCRIPTION
**Pull request by shabiel**
Medications are recorded as being chronic or not in the models (default
is false). Once recorded as chronic, each time a patient is prescribed
the medication an initial time, it will be kept track of in the Person
class. Then at each wellness encounter, the medication will be renewed
until it is discontinued or the patient dies.

Detailed Implementation Notes:
- Person.chronicMedications is a new hash map that keeps track of
  medications.
- HealthRecord.Medication, State.MedicationOrder both now have a chronic
  flag.
- HealthRecord.Encounter has a flag for tracking weather meds were
  renewed at this encounter. This is a dirty hack, but was necessary as
  the code for Wellness encounter in State.Encounter.process was being
  run multiple times, once for each module that waited for the Wellness
  encounter. I want a better idea for doing this. The other ways to do
  this take too much processing time (going through each medication like
  we do for diagnoses; or checking each medication for the time it was
  last renewed).
- HealthRecord.medicationStart now take a boolean parameter to
  indication whether a medication is chronic. If it is, it is added to
  Person.chronicMedications. HealthRecord.medicationEnd checks for the
  chronic flag on each medication being ended and removes it if so from
  Person.chronicMedications.
- In State.MedicationOrder.process, recognize chronic meds from models.
  Chronic flag passed to HealthRecord.medicationStart.
- In State.Encounter.process, code to renew chronic medications at each
  wellness encounter. Uses Person.chronicMedications & HealthRecord.
  medicationStart/.medicationEnd.
- Modify Hypertension (hypertension.json) model to add chronic flag to
  each medication. Also, while I was at it, I created full prescriptions
  for each medication.
- Update Java code Cardiovascular model to do chronic meds.
- Update Unit Tests for HealthRecord.medicationStart.

Before and After Visualizations:
Before:
Screen Shot 2019-09-10 at 4 23 09 PM

After:
Screen Shot 2019-09-10 at 4 26 14 PM

### CODE REVIEW

**Comment by jawalonoski** [comment]
Basically, I approve this PR. But the build seems to be broken because Travis/gradle/maven is unable to resolve the HAPI dependencies... I'll merge it after I can figure out why it fails or fix it.....

**Comment by shabiel** [comment]
Anything I can do to help? Is there a way to resubmit it to Travis?

**Comment by jawalonoski** [comment]
Found this:
> In addition, a new HAPI FHIR release (4.0.1) has been uploaded to the Maven Central repos. This release contains no new or updated functionality, but addressed a dependency version that was left incorrectly requiring a SNAPSHOT maven build of the org.hl7.fhir.utilities module. Users who are successfully using HAPI FHIR 4.0.0 do not need to upgrade, but any users who were blocked from upgrading due to snapshot dependency issues are advised to upgrade immediately.

Source: http://hapifhir.io under September 3rd Announcement.

Trying to update and see if that fixes the problem...

**Comment by shabiel** [comment]
Now I can get some champagne for my first successful pull request into Synthea!

**Comment by shabiel** [comment]
Also, don't forget my PR on the module-builder.

**Pull request merged**
