### PR TITLE
Updated Ruby 2.4 support patch.

### PR DESCRIPTION
**Pull request by preston**
Related to #199 and #200. Obsoletes #202.

### CODE REVIEW

**Comment by jawalonoski** [comment]
@preston Please add change your health data standards reference to:

```
gem 'health-data-standards', git: 'https://github.com/projectcypress/health-data-standards.git', branch: 'ruby_24'
```

Also, please use this `.rubocop.yml` file to get Travis back to "green":

```
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - 'lib/world/MA_geo.rb'
    - 'lib/records/lookup.rb'
    - 'lib/records/shr_mapping.rb' # ignored because generated code
    - 'lib/tasks/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics:
  Enabled: false

Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Security/YAMLLoad:
  Enabled: false
```

**Comment by preston** [comment]
@jawalonoski: Should I resubmit this PR, or are you making the changes directly?

**Comment by jawalonoski** [comment]
I was waiting for the requested changes, but I think that #205 functionally did the 2.4 upgrade.

**Comment by preston** [comment]
Ok

**Pull request closed without merging**
