### PR TITLE
Fix incorrect RxNorm codes in Synthea

### PR DESCRIPTION
**Pull request by shabiel**
Reasoning for all changes is in the commit messages. Addresses #469.

### CODE REVIEW

**Comment by jawalonoski** [comment]
@shabiel Did you check to see if any of these codes ended up requiring changes to the costs file? https://github.com/synthetichealth/synthea/blob/master/src/main/resources/costs/medications.csv

**Comment by shabiel** [comment]
Jason,

I totally forgot about that file. Yes, I need to change it. Since I
didn't change the drugs; just the codes to represent them; the prices
should theoretically be still the same.

--Sam

**Comment by shabiel** [comment]
I changed the costs file. I ran the query against the Medicare Part D
costs, and not surprisingly, most of the costs have changed. Note that
the API does not provide provide "mean" price, which is what you want
in your table. I have calculated averages instead.

For posterity, here is a sample API call:
```
Macintosh:synthea sam$ curl
'https://data.cms.gov/resource/xbte-dn4t.json?$select=generic_name,MIN(total_drug_cost/total_claim_count),MAX(total_drug_cost/total_claim_count),AVG(total_drug_cost/total_claim_count),stddev_pop(total_drug_cost/total_claim_count)&$group=generic_name&$where=starts_with(generic_name,%20%27HYDROCODONE%27)'
[{"generic_name":"HYDROCODONE/ACETAMINOPHEN","MIN_total_drug_cost_total_claim_count":"1.1133333333333333","MAX_total_drug_cost_total_claim_count":"2424.0390909090909091","AVG_total_drug_cost_total_claim_count":"21.2834746462112582","stddev_pop_total_drug_cost_total_claim_count":"25.19753263702106296904112003197859"}
,{"generic_name":"HYDROCODONE
BITARTRATE","MIN_total_drug_cost_total_claim_count":"91.8681818181818182","MAX_total_drug_cost_total_claim_count":"2040.7563636363636364","AVG_total_drug_cost_total_claim_count":"432.7168910805332081","stddev_pop_total_drug_cost_total_claim_count":"160.53092471924846072385679698566030"}
,{"generic_name":"HYDROCODONE BIT/HOMATROP
ME-BR","MIN_total_drug_cost_total_claim_count":"11.0430769230769231","MAX_total_drug_cost_total_claim_count":"37.4692857142857143","AVG_total_drug_cost_total_claim_count":"19.3805525037350328","stddev_pop_total_drug_cost_total_claim_count":"6.17488993151132791134192303371990"}
,{"generic_name":"HYDROCODONE/IBUPROFEN","MIN_total_drug_cost_total_claim_count":"1.1958823529411765","MAX_total_drug_cost_total_claim_count":"656.6758333333333333","AVG_total_drug_cost_total_claim_count":"46.2185827565266057","stddev_pop_total_drug_cost_total_claim_count":"47.55292580273287331718768364955518"}]
```

**Comment by jawalonoski** [comment]
Maybe we should think about turning your `curl` command above, and your bash script in #469 into utilities that are bundled with Synthea in a `scripts/` folder.

**Pull request merged**
