### PR TITLE
Initial Commit of HealthsparqCPCDSExporter and other contributions

### PR DESCRIPTION
**Pull request by jlund-healthsparq**
Minor changes to the .gitignore to support intellij
change to the export/Exporter class to support the HealthsparqCPCDSExporter class
Minor syntax change in the helpers/ExpressionProcessor class comments/docs to support actual inputs
Added methods to setDeductible and getDeductible in the world/agents/Person class
Added a discrete ClaimCosts class in world/concepts
Implemented the ClaimCosts class in the world/concepts/Claim class
Implemented the ClaimCosts class in the world/concepts/HealthRecord class
Added elements to the synthea.properties file to allow exporting via the HealthsparqCPCDSExporter
Added Mocking of Person, Healthrecord.Encounter, Healthrecord.Procedure, Codes, and Payers to the TestHelpers
Added a note to the Utilities test explaining that the test testYears fails when run in late December each year
Updated the PayerTest to handle coinsurance also
Added a new test class (and tests) to test the ClaimsCost class

The following changes are all Snomed to ICD10 related changes.  The classes have been added but the config data is not committed due to licencing issues.
    A README to explain how to implement ICD10 translations has been added at 
 world/concepts/ICD10README.md 
    Added a world/concepts/SnomedConversion class that can be implemented by exporters
    Added the possibility for the world/concepts/HealthRecord/Code to report codes in ICD10
        When an ICD10 code is found without a descriptor then the descriptor is left as the Snomed equivalent.
        Methods are also added to expose these states
    Added a new test class to test the SnomedConversion class

### CODE REVIEW

**Comment by jawalonoski** [comment]
Why do we need a `HealthsparqCPCDSExporter` class in addition to the `CPCDSExporter` class?

What is the strategy in the future for these two exporters? Should they be merged?

Can @jlund-healthsparq or @mosiermt explain the difference between this PR and #635 ?

**Comment by mosiermt** [comment]
#635 Is to update the current CPCDSExporter class to keep up with the most recent Carin BB implementation of CPCDS.  This includes exporting of EoB's for Inpatient, Outpatient, Pharmacy, and Professional/Non-Clinician.  From looking at the code in this PR, it seems to be a different implementation of CPCDS.  I am not familiar with the particular standard used in this PR, but I don't see the fields for pharmacy or non-clinician claims being populated. As for the patient file, the two seem to be largely the same. Coverage files seem to be pretty different.  I have linked the documentation for my CPCDS implementation in #635.  Is there a link for the documentation of the IG used here?

**Comment by jlund-healthsparq** [comment]
@jawalonoski and @mosiermt I apologize for the confusing pull request.

The intent was to provide visibility to current Healthsparq progress implementing the CPCDS output format using Synthea data generation.  We did not target a different standard, however our understanding is that the standard is flexible enough to handle extra fields and the branch is also intended to represent some potential different approaches that we took.  I have attached out internal documentation to represent the standard that we are working to.
[ENG-HealthsparqCPCDSOutputDataSpecification-100120-1207-74.pdf](https://github.com/synthetichealth/synthea/files/4047149/ENG-HealthsparqCPCDSOutputDataSpecification-100120-1207-74.pdf)


Some differences include;

- not implementing pharmacy claims since only the prescription is listed not the actual medication from the pharmacy.  There is a thought that the pharmacy (and Generic vs Brand medication selection) should be randomized and added before filling the pharmacy claim.
- We added a very rough pass at a SNOMED to ICD10 translator based on the information available @ https://www.nlm.nih.gov/research/umls/index.html  - This is a backwards compatible implementation that should have minimal impact for anyone who has not loaded the lookup tables to their repo and is only implemented in the exporter.
- Adding a Claim Costs class in order to handle the fairly complex tracking of Copay, Deductable, and Coinsurance
- Editing the Healthrecord.Code class to allow for ICD10 and SnoMed codes to display as well as methods to determine if a successful translation was made.  -  This should also be a non-breaking change
- Some test helpers to provide mock implementations of Person, Encounter, Procedure, list of Codes, a no insurance Payer, and a regular Payer

I had intended to push this sooner but several internal infrastructure/release fires unrelated to Synthea occurred.  I also took a two week holiday break and am just getting back on top of my various projects.  I actually have one more push that I expect to make next week with a re-implementation of the CPCDS exporter as a config file driven set that should allow technical non-devs to make export tweaks.  This should have made it out sooner as well but when I added some final tests I identified an architectural issue that needed some rework in my initial submission.

**Comment by jawalonoski** [comment]
@jlund-healthsparq Thank you for the pull request. Apologies, I have only begun to look at it.

I'm reluctant to have multiple CPCDS export formats, but we do it for FHIR, so I could be persuaded as long as this format is openly and publicly documented, which it appears to be (since you provided the link).

However, I'm less keen on terminology code translation being jammed into the same pull request. I have avoided this for a while, and we have an existing (albeit old) PR on integrating terminology services such as VSAC for these type of translations. I need time to dig into this...

**Comment by jlund-healthsparq** [comment]
@jawalonoski Thank you for taking a look.  Your comments totally make sense.  I think that if you are not interested in the translation piece on the main repo but if the other stuff looks interesting then I can pull it back out and create a new pull request.  Additionally, I have been delayed in some additional changes that I wanted to present.  Take your time with the review.

**Comment by jawalonoski** [comment]
@jlund-healthsparq Apologies for the delay... I'm ready to take this, but...

Yes, please make the translation piece a separate PR. I'm warming up to the idea, but I'd like to consider it separately.

Also, there have been a few other PRs merged in, which has caused some conflicts. Please fix these. Sorry! This is my fault, since they were not there when you originally submitted the PR.

Thank you for your patience and support!!

**Comment by jlund-healthsparq** [comment]
No problem,  This has kind of moved to a back burner for me so It's going to be a week or so before I can provide the updates

**Comment by jawalonoski** [comment]
Thank you for the pull request, but I'm going to close this for now as it has become rather out of date and there are too many conflicts to fix.

**Pull request closed without merging**
