### PR TITLE
covid19 module

### PR DESCRIPTION
**Pull request by jawalonoski**
> ⚠️ Please do not use this module or the resulting data to make clinical decisions. This is a module is informed by emerging research. There are many unknowns about COVID19 and there are likely mistakes in the treatment and outcomes.

This pull requests adds a COVID-19 disease module that simulates the pandemic outbreak.

This pull request addresses #679.
Currently the module is composed of many submodules (see table below). The general arc or pathway starts with the determination of the probability of infection. If infected, each patient is grouped by risk and severity. Outcomes are dependent on severity.

## Modules

Module | Description
--------|------------
| `covid19` | Determines exposure and infection rates.
| `covid19/admission` | Contains the daily loop during hospitalization and ICU treatment.
| `covid19/determine_risk` | Determines risk based on comorbidities, severity of disease, and whether or not the patient will survivor.
| `covid19/infection` | Determines whether or not patients will be testing, the testing results, and whether or not they are admitted to the hospital.
| `covid19/medications` | Potentially enrolls some patients into one of twelve clinical trials.
| `covid19/measurements_daily` | Records daily lab values.
| `covid19/measurements_frequent` | Records frequent lab values.
| `covid19/nonsurvivor_lab_values` | Sets lab values for patients who will not survive.
| `covid19/survivor_lab_values` | Sets lab values for patients who will survive.
| `covid19/outcomes` | Determines outcomes and complications based on risk and disease severity.
| `covid19/end_outcomes` | Ends complications after recovery (if applicable).
| `covid19/supplies_hospitalization` | Contains the daily supplies used within the hospital for documented patient:provider ratios.
| `covid19/supplies_icu` | Contains the daily supplies used within ICU for documented patient:provider ratios.
| `covid19/supplies_intubation` | Contains the supplies used for intubation.
| `covid19/symptoms` | Determines the symptoms presenting in each patient
| `covid19/end_symptoms` | Ends symptoms after recovery (if applicable).
| `covid19/diagnose_blood_clot` | Patient will likely develop blood clots during their stay.
| `covid19/treat_blood_clot` | Blood clots need to be treated once they are developed.
| `covid19/diagnosed_bacterial_infection` | Some patients will develop secondary bacterial infections.

## Analysis of Results

[Synthea COVID-19 Analysis.pdf](https://github.com/synthetichealth/synthea/files/4689250/Synthea.COVID-19.Analysis.pdf)

## Primary citations:

- Fei Zhou, Ting Yu, Ronghui Du, Guohui Fan, Ying Liu, Zhibo Liu, Jie Xiang, Yeming Wang, Bin Song, Xiaoying Gu, Lulu Guan, Yuan Wei, Hui Li, Xudong Wu, Jiuyang Xu, Shengjin Tu, Yi Zhang, Hua Chen, Bin Cao. **Clinical course and risk factors for mortality of adult inpatients with COVID-19 in Wuhan, China: a retrospective cohort study.** The Lancet, Volume 395, Issue 10229, 2020, Pages 1054-1062, ISSN 0140-6736, https://doi.org/10.1016/S0140-6736(20)30566-3.
  - This paper was used for disease severity status, determination of outcomes, hospital and ICU length of stay, and trends in key lab values.
- Guan WJ, Ni ZY, Hu Y, Liang WH, Ou CQ, He JX, Liu L, Shan H, Lei CL, Hui D, et al. **Clinical characteristics of coronavirus disease 2019 in China.** N Engl J Med. 2020. PMID: 32109013. https://doi.org/10.1056/NEJMoa2002032.
  - This paper was used for disease severity status, distribution of symptoms, key lab values.
- Richardson S, Hirsch JS, Narasimhan M, et al. **Presenting Characteristics, Comorbidities, and Outcomes Among 5700 Patients Hospitalized With COVID-19 in the New York City Area.** JAMA. Published online April 22, 2020. http://doi.org/10.1001/jama.2020.6775
  - This paper was used for mortality data.
- Other sources documented in #679 and the module "remarks"

### CODE REVIEW

**Comment by jawalonoski** [comment]
That last commit now allows you to set a `range` on the `SetAttribute` state. This was useful to create different ranges and progressions of lab values for survivors and non-survivors (i.e. some spike, some drop).

**Comment by jawalonoski** [comment]
My next steps are likely to refine the progression of complications and treatments which diverge between survivors and non-survivors. I may or may not make these submodules.

**Comment by jeffeastman** [comment]
+1 for submodules

**Comment by jawalonoski** [comment]
OK, the `covid19` branch works at this point (no exceptions), but codecov is angry because of the lack of unit tests on the changes made. But travis successfully builds and tests.

**Comment by jawalonoski** [comment]
For anyone who is following this monster, the previous commit breaks up `covid19/infection` into:

```
	new file:   src/main/resources/modules/covid19/admission.json
	new file:   src/main/resources/modules/covid19/daily_measurements.json
	new file:   src/main/resources/modules/covid19/end_outcomes.json
	modified:   src/main/resources/modules/covid19/infection.json
	new file:   src/main/resources/modules/covid19/outcomes.json
```

 - `admission` contains the daily loops for hospitalizations and ICU admissions
 - `daily_measurements` contains the daily lab work and observations
 - `outcomes` includes the determinations of the outcomes and complications
 - `end_outcomes` ends the acquired conditions in `outcomes` (assuming the patient survives)
 - `infection` now just includes the logic about the COVID19 testing, care plans, and whether or not to admit patients (if so, they dump into `admission`). This is still the main submodule.

**Comment by jeffeastman** [comment]
Hi Jay,

I’m seeing a couple of problems running these (great) new modules in PatientGen:

admission module "Extubation_Check" state has a transition to "Compassionate Care” which should probably be "Compassionate_Care"
admission module has several states with reason "Respiratory Distress” which is not defined in the module

BTW Super job of refactoring the infection module into such useful submodules. It was getting impossibly huge and this was sorely needed.

Jeff

**Comment by jawalonoski** [comment]
The last commit created a new submodule `covid19/medications.json` that potentially enrolls a small amount of patients in one of 12 clinical trials. The outcomes are not altered based on the medications administered.

**Comment by jawalonoski** [comment]
The next commit will update the `covid19/medications` submodule based on the following table:

image

**Pull request merged**
