### PR TITLE
Other usa states

### PR DESCRIPTION
**Pull request by jawalonoski**
See #206 

You can now drop in new 2010 census data files in `./resources` for states other than Massachusetts.

Remaining issues: you won't get proper zip codes (they'll show up as `"XXXXX"`) without further changes and you won't get lat/lons in the `Patient` resources.

### CODE REVIEW

**Comment by jawalonoski** [comment]
I tested this with data for Indiana posted here https://github.com/synthetichealth/synthea/files/1514161/resources.zip from #206

**Comment by jawalonoski** [comment]
These changes should more or less address #131, #206, and #246 by including a `resources/demographics.csv` file that includes all demographics for the entire United States.

If you want to generate another country (e.g. Netherlands or the United Kingdom), you can do it by replacing `resources/demographics.csv` with a CSV file. The structure of the CSV file will be documented in the wiki here.

**Comment by dehall** [comment]
Why are so many cities in the demographics.csv file missing the income and education columns? We have that data for every city in MA in config/towns.json so it must be in the census data

**Comment by dehall** [comment]
A couple other notes, that I don't think can or should be fixed immediately now but should be pointed out:

 - All provider names are still MA provider names. The provider addresses don't seem to be exported in the patient FHIR so it's not obvious but it's still only MA providers. Not a major issue. 
 - A good number of the incidence and prevalence numbers that we use are based on MA data, so the statistics will not necessarily match up to the state's real data. (Ex. diabetes prevalence - MA is 8.0%, CO is 6.4%, MS is 13.6% -- https://gis.cdc.gov/grasp/diabetes/DiabetesAtlas.html )   We'll need to keep this in mind as we update the modules and engine.

**Comment by jawalonoski** [comment]
Regarding missing data: it seems to  do with regional variation in the census areas. I can get the data for all of those cities, just not easily. Currently I'm working of a single geography entitled "All Places within United States and Puerto Rico" which allows me to download a giant file.. to get the missing information (e.g. Acton, MA), I'd have to look at each State and merge them in.

**Comment by dehall** [comment]
Ok. Overall this looks good, with the noted limitations. There are also publicly available data sources with zip codes and city boundaries, though the GeoJSON for the boundaries of all cities in the US is > 200 MB and maybe not something we want to include directly. (For comparison the MA GeoJSON we include currently is ~3 MB)

**Pull request merged**
