### PR TITLE
Added UTI Module

### PR DESCRIPTION
**Pull request by cjduffett**
Created a module to model urinary tract infections. 50% of women will get at least one UTI in their lifetime, with some getting 2 or 3. In rare cases women can also get recurring UTIs that happen every 2-4 months for life. UTIs are rare for males but about 1 in 20 will get 1.

### CODE REVIEW

**Comment by cjduffett** [comment]
For reference:

urinary tract infections

**Comment by dehall** [comment]
1 - the first round of antibiotics doesn't get ended if it's effective. probably want to move the distributed transition from Take_Antibiotics to End_First_Round_of_Antibiotics.
2 - recurring UTIs happen for life?
3 - I'm not a huge fan of choosing in advance how many UTIs a person will get. I know I'm guilty of doing the same thing in a couple modules but for conditions that can occur repeatedly I feel like it's defining the model too tightly to the real prevalences / "overfitting". @jawalonoski I'd like to know your thoughts on that as well.

**Comment by jawalonoski** [comment]
Yeah, not a huge fan of overfitting as Dylan describes... the prevalences will change based on the region.

**Comment by cjduffett** [comment]
I updated the module to probabilistically give men and women additional UTIs (rather than determining that up-front). Also added a CarePlan to the module.

**Comment by cjduffett** [comment]
urinary tract infections

**Pull request merged**
