### PR TITLE
Fixed Injury Care Plans

### PR DESCRIPTION
**Pull request by cjduffett**
All injury care plans are now guaranteed to be concurrent with their `target_encounter`. Fixes [Issue #118](https://github.com/synthetichealth/synthea/issues/118).

### CODE REVIEW

**Comment by dehall** [comment]
This failed silently and it required a close review of the module to find the issue. Does it make sense to change the logic in CarePlanStart (and ConditionOnset, MedicationOrder, and Procedure) so that it raises an exception if not concurrent with the target encounter, instead of just doing nothing? Ideally I would prefer some kind of validation that these states will always be concurrent with the target encounter, but I'm not sure where that would fit in the existing validation framework.

**Comment by jeffeastman** [comment]
+1 Its hard enough to debug the modules when everything thats supposed to happen occurs. The silent omission of an element because of a timing issue makes debugging much more difficult. Due to the complexity of the flows, static analysis to detect these situations seems challenging too. I’d be interested in a discussion of static validation but in the mean time an exception would be useful to force the resolution.

Jeff

**Comment by cjduffett** [comment]
Good point @dehall, I'll add that to `concurrent_with_target_encounter()`.

**Comment by cjduffett** [comment]
I added two checks to the states:

1. Only `ConditionOnset` states are allowed to come before their `target_encounter` state. All other clinical states now raise an exception if the `target_encounter` is not found in the module's history when the clinical state is reached.
2. If any clinical state other than a `ConditionOnset` is not recorded because it's not concurrent with its `target encounter`, an exception is raised.

**Pull request merged**
