### PR TITLE
Medication Submodules

### PR DESCRIPTION
**Pull request by cjduffett**
These were the O.G. submodules that I finally got around to compiling and integrating with our existing modules. I created several different submodules that prescribe commonly used medications across several main modules:

* OTC Pain Relievers
* OTC Antihistamines
* Moderate Opioid Pain Relievers (post surgery, or for injuries)
* Strong Opioid Pain Reliever (for chronic pain, e.g. cancer)
* Ear Infection Antibiotic (also used for bacterial infections due to burns/open wounds)

The Strong Opioid Pain Reliever module isn't actually used yet - I expected the cancer modules to prescribe a strong opioid for chronic pain but neither one does. I will go back in and add a strong pain reliever for the late stages of cancer if my approach so far tickles your fancy.

I made updates to some of our modules to use these submodules, namely:

* Allergies/Allergic Rhinitis (otc_antihistamine)
* Ear Infections/Injuries (ear_infection_antibiotic)
* Injuries, surgery (moderate opioid)
* Numerous modules for otc pain reliever

I made a couple of fixes to existing modules as I encountered them, including a partial refactoring where I removed `target_encounter` states, added `duration` fields to procedures, and added `prescription` information to MedicationOrder states. There are still **many** states to refactor this way but I figure it will be a passive effort as we periodically go back in and edit existing modules.

Would love to hear you feedback to see what you like, or what you think may need improvement/expansion.

### CODE REVIEW

**Comment by jawalonoski** [comment]
These changes look fine. I want to do a more thorough review before these are merged, and I do **not** want these merged while the module validation is ongoing.

**Comment by jawalonoski** [comment]
This pull request seems to break medication export in CCDA.

```
Problem:
  Value of type Fixnum cannot be written to a field of type Hash
Summary:
  Tried to set a value of type Fixnum to a field of type Hash
Resolution:
  Verify if the value to be set correspond to field definition
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes.rb:341:in `validate_attribute_value'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes.rb:169:in `block in write_attribute'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes.rb:168:in `write_attribute'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/fields.rb:457:in `block (2 levels) in create_field_setter'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes/dynamic.rb:102:in `process_attribute'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:25:in `block in process_attributes'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:23:in `each_pair'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:23:in `process_attributes'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/document.rb:110:in `block in initialize'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/threaded/lifecycle.rb:84:in `_building'
/.rvm/gems/ruby-2.3.0/gems/mongoid-4.0.0/lib/mongoid/document.rb:104:in `initialize'
/git/synthea/lib/records/ccda.rb:181:in `new'
/git/synthea/lib/records/ccda.rb:181:in `medications'
/git/synthea/lib/records/ccda.rb:17:in `block (2 levels) in convert_to_ccda'
/git/synthea/lib/records/ccda.rb:11:in `each'
/git/synthea/lib/records/ccda.rb:11:in `block in convert_to_ccda'
/git/synthea/lib/records/ccda.rb:9:in `each'
/git/synthea/lib/records/ccda.rb:9:in `convert_to_ccda'
/git/synthea/lib/records/exporter.rb:8:in `export'
/git/synthea/lib/world/sequential.rb:173:in `block in run_random'
/git/synthea/lib/world/sequential.rb:332:in `run_task'
/git/synthea/lib/world/sequential.rb:170:in `run_random'
/git/synthea/lib/world/sequential.rb:83:in `run'
lib/tasks/tasks.rake:62:in `block (2 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/.rvm/gems/ruby-2.3.0/bin/rake:22:in `load'
/.rvm/gems/ruby-2.3.0/bin/rake:22:in `<main>'
/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by cjduffett** [comment]
So the issue is that I'm trying to assign a numeric (`Fixnum`) value to `FulfillmentHistory.quantityDispensed`, but that value is explicitly of type `Hash`:

```

class FulfillmentHistory
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  
  field :prescriptionNumber, as: :prescription_number, type: String
  field :dispenseDate, as: :dispense_date, type: Integer
  field :quantityDispensed, as: :quantity_dispensed, type: Hash
  field :fillNumber, as: :fill_number, type: Integer
  field :fillStatus, as: :fill_status, type: String
  
  belongs_to :provider, class_name: "Provider"

  def shift_dates(date_diff)
    self.dispenseDate = (self.dispenseDate.nil?) ? nil : self.dispenseDate + date_diff
  end
end
```

Unfortunately the complete lack of documentation for this gem leaves me unsure how to fix this. Is there a special `Quantity` hash that's supposed to be assigned to this field to represent a quantity?

If not, what is the hash I need to use here supposed to look like? @jawalonoski, maybe you can shed some light on this?

**Comment by jawalonoski** [comment]
See https://github.com/projectcypress/health-data-standards/blob/master/test/fixtures/records/barry_berry.json#L369

**Comment by jawalonoski** [comment]
The issue referenced above is probably fixed with #154 

We'll have to retest this PR after #154 has been merged.

**Comment by cjduffett** [comment]
Rebased with the latest updates from master. @jawalonoski, thanks for fixing the CCDA export. I ran a sequential run with CCDA export enabled and it looks like the medications are being exported correctly now.

**Pull request merged**
