### PR TITLE
New Cerebral Palsy Module

### PR DESCRIPTION
**Pull request by casey7083**
This module models the treatment of Sialorrhea in Cerebral Palsy in patients age <=18 years of age. It is based on the American Academy for Cerebral Palsy and Developmental Medicine (AACPDM) clinical care pathway for Sialorrhea. This guideline provides recommendations for treatment of Sialorrhea in outpatient settings for the pediatric patient with cerebral palsy. 
While this module contains other conditions that may occur in the cerebral palsy patient, such as dystonia, pain, spasticity, central hypotonia, osteoporosis, epilepsy, gastroesophageal reflux disease, and intellectual disability, treatments for these conditions are not yet modeled in the module.
[20200923_Module_Companion_Guide_Cerebral Palsy_clean.docx](https://github.com/synthetichealth/synthea/files/5308394/20200923_Module_Companion_Guide_Cerebral.Palsy_clean.docx)

### CODE REVIEW

**Comment by jawalonoski** [comment]
@casey7083 Thank you for the pull request. We are a little behind reviewing and merging pull requests these days. Thank you for your patience!

**Comment by jawalonoski** [comment]
Apologies for the delay. Clinician review was quick, but the delay was me and my schedule. So, I apologize for that.

The clinician review only provided a single suggestion, which was to be more consistent with the use of the "reason" field.

- Please provide the condition as "reason" for prescribed medications and procedures.
  - For example, see the [Examplitis Module](https://synthetichealth.github.io/module-builder/#example_module), where the Examplitol MedicationOrder and the Examplotomy Procedure both provide the "reason" as the Examplitis ConditionOnset.

[CPReview_2020-10-22.docx](https://github.com/synthetichealth/synthea/files/5430151/CPReview_2020-10-22.docx)

**Comment by casey7083** [comment]
Thanks for the feedback! I will incorporate the recommended changes.

**Comment by jawalonoski** [comment]
A few more notes after running this module, you probably also want to add the "reason" to the `Followup_Cerebral_Palsy_Encounter` state, and other encounters. It helps during analysis.
 
Also, you need to move the `cerebral_palsy.json` file to be located in `src/main/resource/modules` rather than the project root folder.

**Comment by casey7083** [comment]
Got it! Will do. Thanks

Casey Thompson MSN, RN-BC | Clinovations Government + Health
Direct: 210.429.5250
casey@govhealth.com<mailto:casey@govhealth.com>

**Pull request closed without merging**
