### PR TITLE
New clinical sepsis module

### PR DESCRIPTION
**Pull request by casey7083**
New sepsis clinical module. See module companion guide for additional module information. Thanks! 
[20201201_Module_Companion_Guide_Sepsis.docx](https://github.com/synthetichealth/synthea/files/5662569/20201201_Module_Companion_Guide_Sepsis.docx)

### CODE REVIEW

**Comment by casey7083** [comment]
Hello, I updated the sepsis file based on clinical feedback received. New file is v2. Thanks. Casey

**Comment by casey7083** [comment]
Updated file to address clinical feedback. Additional information available in the Module Companion Guide. 
[20201215_Module_Companion_Guide_Sepsis.docx](https://github.com/synthetichealth/synthea/files/5697853/20201215_Module_Companion_Guide_Sepsis.docx)

**Comment by casey7083** [comment]
Added new sepsis file to address clinical feedback. Removed v2 sepsis file with wrong name. Updated Module Companion Guide attached for additional information. Thanks! 
[20201216_Module_Companion_Guide_Sepsis.docx](https://github.com/synthetichealth/synthea/files/5703870/20201216_Module_Companion_Guide_Sepsis.docx)

**Comment by jawalonoski** [comment]
Any objections to putting a random `Delay` state between `Age_Guard` and `Sepsis`?

Right now, 6% of the population gets sepsis immediately at age 18. A Delay will spread this out.

For example:
image

**Comment by casey7083** [comment]
No concerns from me. Thanks! I can add if you need me to.

Casey Thompson MSN, RN-BC | Clinovations Government + Health
Direct: 210.429.5250
casey@govhealth.com<mailto:casey@govhealth.com>

**Comment by jawalonoski** [comment]
@casey7083 I'll take care of it. Thank you for the quick reply!

**Comment by casey7083** [comment]
Thank you!! Let me know if you see anything else. Appreciate your help with this.

Casey Thompson MSN, RN-BC | Clinovations Government + Health
Direct: 210.429.5250
casey@govhealth.com<mailto:casey@govhealth.com>

**Pull request merged**
