### PR TITLE
Mihin covid 19

### PR DESCRIPTION
**Pull request by jeffeastman**
This patch introduces an attribute "Ventilator Reason" which is assigned by "Septic Shock" and "Respiratory Failure", two paths which lead to the "Ventilation" procedure.

### CODE REVIEW

**Comment by jeffeastman** [comment]
This patch works in my environment and avoids my GMF's unresolved reason exception

**Comment by jawalonoski** [comment]
@jeffeastman, I can't merge this, you are deleting three of the covid19 submodules in this PR.

**Comment by jeffeastman** [comment]
Really? Clearly not my intent. Investigating...

**Comment by jeffeastman** [comment]
Closing because of new pull request

**Pull request closed without merging**
