### PR TITLE
Injuries 2.0

### PR DESCRIPTION
**Pull request by cjduffett**
I reworked the injuries module to give more realistic injuries to the population. Two issues we were facing with the previous injuries module was a lack of variety in the injuries people were getting and too high incidence for those injuries. I solved this by adding more variety to the injuries people can get (see the table below) and by reducing the incidence rates.

The incidence of opioid addiction is still WAY to high but I will address that in a separate pull request since that mainly involves reworking the opioid addiction module.

I simulated 10,000 patients over the course of the day and checked the prevalence at the end of the simulation. At present, we have the following injuries and rates:

| Injury | Prevalence | Notes |
|:------|:------------|:------|
| Sprains | 0.7% | This may seem low but a lot of sprains aren't treated in an ED setting. They just heal on their own. |
| Concussions | 5.2% | |
| Whiplash | 3.0% | |
| Spinal | 0.045% | Fracture of the spine. Some lead to permanent neurological damage or even death. |
| Gunshots | 0.015% | | 
| Lacerations | 7.6% | Many different body areas (hands, legs, arms, face) represented. |
| Fractures | 16.3% | This percentage may seem high but many people (especially children) will break a bone of some kind in their lifetime.|
| Knees | 0.9% | Torn ligaments, torn meniscus, etc. |
| Shoulders | 0.38% | Torn rotator cuff |
| Burns | 1.25% | First, Second, and Third degree burns at varying rates. |

I don't claim to be an expert and I'm open to feedback if any of these seem too low or high. I also don't model the cause of these injuries, only that they occurred. Causes could include falls, sports, car accidents, wartime, etc. but no distinction is made at this time.

Currently I vary incidence only by age ranges - not by gender or socioeconomic status. That complexity could be added but I wanted to test the simplest case first and see how things came out.

The other diseases we track currently have the following prevalence:

| Disease | Prevalence |
|:--------|:------------|
| Heart Disease | 7.3% |
| Opioid Addiction | 19.4% |
| Lung Cancer | 1.61% |

This image may be too big to view directly on GitHub (in that case just generate it yourself using graphviz) but here's the new injuries flow chart:

injuries

Note the distinct separation between incidences (the cluster at the top) and the progression of the injury (once it occurs). I think this overall design helps us more easily tune incidences without affecting the rest of the injury's progression.

### CODE REVIEW

**Comment by cjduffett** [comment]
To be honest I'm not totally wild about the way I handled incidence for these injuries. I think I'm going to split each into its own module (at the cost of duplicating some states) to make things a little clearer and easier to fine-tune.

**Comment by jawalonoski** [comment]
Presumably those are generated prevalences in the tables --- please also add expected prevalence rates.

**Comment by jawalonoski** [comment]
On average, how many childhood (under 18) injuries does this model generate? Over the lifetime?

**Comment by dehall** [comment]
1 - I think scaling the total incidence numbers by the population grouping %s means the resulting numbers are too low. You get that "scaling" factor for free when you split the population by age anyway. I know I'm not explaining this very well.

2 - A couple places refer to a "fatal_injury" attribute which isn't used anywhere else

**Comment by cjduffett** [comment]
@dehall, I agree with you.

1. I fixed the initial incidence numbers (the same for each age group) and the results look a lot more realistic.
2. I envisioned the `fatal_injury` attribute to be used by a self-harm module. A lot of suicides are the result of gunshot wounds.

**Comment by cjduffett** [comment]
At Dylan's suggestion I omitted most of the modules except opioids and injuries to speed up the generation of 10k patients. I will add those back into the next run though to get a count for lung cancer and heart disease.

At a glance these prevalences seem pretty good. Fractures are too high for adults and too low for children, so I'm fixing that in the next run. I also think there are too few concussions. Besides opioid addiction, is there anything else you guys notice that's off?

## Diseases

| Disease | Pop (out of 11k) | Est. Prevalence | Act. Prevalence | Act. Incidence | Source |
|:---------------|:----------------:|:---------------:|:---------------:|:--------------:|:-------|
| Diabetes | 1201 | 10.8% | 9.3% | 0.439% | [ADA](http://www.diabetes.org/diabetes-basics/statistics/)|
| Opioids | 2384 | 21.5% | 0.668% | - | [NIH](https://www.drugabuse.gov/about-nida/legislative-activities/testimony-to-congress/2016/americas-addiction-to-opioids-heroin-prescription-drug-abuse) |
| Heart Disease | - | - | 11.5% | 0.262% | [CDC](http://www.cdc.gov/nchs/fastats/heart-disease.htm)|
| Lung Cancer | - | - | 0.157% | 0.0705% | [ALA](http://www.lung.org/lung-health-and-diseases/lung-disease-lookup/lung-cancer/learn-about-lung-cancer/lung-cancer-fact-sheet.html?referrer=https://www.google.com/)|

## Injuries

| Injury | Pop (out of 11k) | Avg. Per Person | Est. Prevalence | Act. Incidence | Source |
|:---------------|:----------------:|:---------------:|:---------------:|:--------------:|:-------|
| Concussions | 391 | 0 - 2 | 3.52% | 0.510% | [NIH](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987636/) |
| Sprains | 3436 | 1 - 4 | 30.97% | 5.44% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Whiplash | 354 | 0 - 2 | 3.19% | 0.478% | [SRI](http://www.srisd.com/consumer_site/epidemiology.htm) |
| Spinal Trauma | 12 | 0 - 1 | 0.0796% | 0.0153% | [NSCISC](https://www.nscisc.uab.edu/PublicDocuments/fact_figures_docs/Facts%202012%20Feb%20Final.pdf) |
| Gunshot Wounds | 31 | 0 - 1 | 0.279% | 0.0318% | [NIH](https://www.ncbi.nlm.nih.gov/pubmed/26116133) |
| Lacerations | 1895 | 0 - 3 | 17.08% | 2.61% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Fractures | 3778 | 1 - 5 | 34.05% | 5.83% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Knee Injuries | 166 | 0 - 1 | 1.496% | 0.229% | [NIH](https://www.ncbi.nlm.nih.gov/pubmed/22506941) |
| Shoulder Injuries | 119 | 0 - 1 | 1.073% | 0.147% | [OJ](http://rheumatology.oxfordjournals.org/content/45/2/215.full) |
| Burns | 296 | 0 - 2 | 2.67% | 0.398% | [BF](http://www.burnfoundation.org/programs/resource.cfm?c=2&a=6) |

### Totals:

Total Patients: 11094  
Deceased: 2948  
Living: 8146

### Note:

Some of these injuries happen regularly but resolve quickly. Therefore incidence is high but prevalence is low or non-existent. For example, gunshot wounds or sprains; they happen quickly and heal quickly (unless the patient dies, of course).

**Comment by jawalonoski** [comment]
Is `Est. Prevalence` the generated prevalence? It looks like it. I can't compare generated prevalence with actual incidence. That is apples and oranges.

**Comment by cjduffett** [comment]
A more complete analysis:

# Synthea: Injuries and Diseases

## Diseases

| Disease | Population Living | Generated Prevalence* | Actual Prevalence | Actual Incidence | Source |
|:--------|:-----------------:|:---------------------:|:-----------------:|:----------------:|:-------|
| Diabetes | 812 | 9.69% | 9.3% | 0.439% | [ADA](http://www.diabetes.org/diabetes-basics/statistics/)|
| Opioids | 2277 | 27.2% | 0.668% | - | [NIH](https://www.drugabuse.gov/about-nida/legislative-activities/testimony-to-congress/2016/americas-addiction-to-opioids-heroin-prescription-drug-abuse) |
| Heart Disease | 894 | 10.7% | 11.5% | 0.262% | [CDC](http://www.cdc.gov/nchs/fastats/heart-disease.htm)|
| Lung Cancer | 3 | 0.0358% | 0.157% | 0.0705% | [ALA](http://www.lung.org/lung-health-and-diseases/lung-disease-lookup/lung-cancer/learn-about-lung-cancer/lung-cancer-fact-sheet.html?referrer=https://www.google.com/)|


## Injuries

### Adjustments:

So far I made the following adjustments to the incidence rates to try and make the injuries a little more realistic:

1. I doubled the fracture incidence for children from `0.0583` to `0.1166`
2. Doubled the child concussion rate from `0.0051` to `0.011` 
3. Increased the adult concussion rate by 1.5 from `0.0051` to `0.00765`
4. Reduced the rate of fractures in adults by half, from `0.0583` to `0.02915`

### Results:

| Injury | Population Living | Generated Prevalence* | Estimated Prevalence** | Actual Incidence | Source |
|:-------|:-----------------:|:---------------------:|:----------------------:|:----------------:|:-------|
| Concussions | 488 | 5.83% | 4.99% | 0.510% | [NIH](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987636/) |
| Sprains | 3395 | 40.5% | 42.8% | 5.44% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Whiplash | 383 | 4.57% | 4.68% | 0.478% | [SRI](http://www.srisd.com/consumer_site/epidemiology.htm) |
| Spinal Trauma | 8 | 0.0955% | 0.153% | 0.0153% | [NSCISC](https://www.nscisc.uab.edu/PublicDocuments/fact_figures_docs/Facts%202012%20Feb%20Final.pdf) |
| Gunshot Wounds | 19 | 0.227% | 0.418% | 0.0318% | [NIH](https://www.ncbi.nlm.nih.gov/pubmed/26116133) |
| Lacerations | 1807 | 21.6% | 23.2% | 2.61% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Fractures | 3180 | 38.0% | 45.2% | 5.83% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Knee Injuries | 174 | 2.08% | 2.27% | 0.229% | [NIH](https://www.ncbi.nlm.nih.gov/pubmed/22506941) |
| Shoulder Injuries | 123 | 1.47% | 1.46% | 0.147% | [OJ](http://rheumatology.oxfordjournals.org/content/45/2/215.full) |
| Burns | 285 | 3.40% | 3.91% | 0.398% | [BF](http://www.burnfoundation.org/programs/resource.cfm?c=2&a=6) |

### Totals:

**Total Patients:** 11590  
**Deceased:** 3213  
**Living:** 8377


### *Generated Prevalence:

This is the percentage of **living** patients with this injury or disease.

### **Estimating Prevalence:

I generated these patients with 10 years of history. Given the actual incidence, we can get an expected value for this 10-year period:

```
expected_value = P(injury)
expected_value = 1 - P(no_injury)
expected_value = 1 - (1 - (incidence) ^ num_years)
```

So, for example, if we had an injury with 5% incidence and we look at 10,000 patients over 10 years, we would expect to see:

```
expected_value = 1 - (1 - (0.95) ^ 10)

expected_value = 
    0.401
```

So we'd expect to see about 40% of the population with a history of that injury after 10 years, or about 4,000 people.

## A Typical Patient's Record

Here's a picture of 10 randomly selected patients out of the 100 I generated with logging turned on. In each column is the number of that type of injury the patient sustained during their lifetime. Note that some of these patients have not yet reached adulthood or old age.

### Full Life:

| Injury     | p0 | p1 | p2 | p3 | p4 | p5 | p6 | p7 | p8 | p9 | Avg. Per Patient |
|:-----------|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:----------------:|
| Concussion | 0 | 0 | 0 | 0 | **1** | 0 | 0 | **1** | 0 | 0 | 0.2 |
| Sprain     | **4** | **5** | **5** | 0 | **4**| **5** | **1** | **2** | 0 | **2** | 2.8 |
| Whiplash   | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | **1** | 0 | 0.2 |
| Spinal     | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Gunshot    | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Laceration | **3** | **1** | 0 | 0 | **3** | 0 | 0 | **2** | **2** | 0 | 1.1 |
| Fracture   | **1** | **4** | **3** | **1** | **4** | **3** | **4** | **2** | **2** | **4** | 2.8 |
| Knee       | 0 | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | **1** | 0.2 |
| Shoulder   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Burn       | 0 | 0 | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0.1 |

### As Children:

| Injury     | p0 | p1 | p2 | p3 | p4 | p5 | p6 | p7 | p8 | p9 | Avg. Per Child |
|:-----------|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:----------------:|
| Concussion | 0 | 0 | 0 | 0 | 0 | 0 | 0 | **1** | 0 | 0 | 0.1 |
| Sprain     | **2** | **3** | **1** | 0 | **2**| **1** | 0 | 0 | 0 | **1** | 1 |
| Whiplash   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | **1** | 0 | 0.1 |
| Spinal     | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Gunshot    | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Laceration | **1** | **1** | 0 | 0 | **2** | 0 | 0 | **1** | **2** | 0 | 0.7 |
| Fracture   | 0 | **2** | **2** | **1** | **2** | **2** | **2** | 0 | **2** | **1** | 1.4 |
| Knee       | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Shoulder   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Burn       | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

In my opinion, I think fractures seem a little high for most patients and concussions a little low. What do you think?

**Comment by jawalonoski** [comment]
Thanks for all the information. This helps. I need to mentally chew on this for a while.

I think fractures are too high. I'd expect 0-2 for most people. I don't know anyone who has had 4 or 5 broken bones. Same for sprains and lacerations.

**Comment by cjduffett** [comment]
Round 2:

# Synthea: Injuries and Diseases

**Iteration 2: 2016-11-17**

## Diseases

| Disease | Population Living | Generated Prevalence* | Actual Prevalence | Actual Incidence | Source |
|:--------|:-----------------:|:---------------------:|:-----------------:|:----------------:|:-------|
| Diabetes | 1025 | 10.26% | 9.3% | 0.439% | [ADA](http://www.diabetes.org/diabetes-basics/statistics/)|
| Opioids | 1980 | 19.81% | 0.668% | - | [NIH](https://www.drugabuse.gov/about-nida/legislative-activities/testimony-to-congress/2016/americas-addiction-to-opioids-heroin-prescription-drug-abuse) |
| Heart Disease | 1046 | 10.47% | 11.5% | 0.262% | [CDC](http://www.cdc.gov/nchs/fastats/heart-disease.htm)|
| Lung Cancer | 3 | 0.0300% | 0.157% | 0.0705% | [ALA](http://www.lung.org/lung-health-and-diseases/lung-disease-lookup/lung-cancer/learn-about-lung-cancer/lung-cancer-fact-sheet.html?referrer=https://www.google.com/)|


## Injuries

### Adjustments:

So far I made the following adjustments to the incidence rates to try and make the injuries a little more realistic:

1. I doubled the concussion incidence for children from `0.0051` to `0.1010`
2. Halved the child fracture rate from `0.0583` to `0.025` 
3. Increased the adult concussion rate by 1.5 from `0.0051` to `0.00765`
4. Decreased the adult fracture rate by a factor of 4, from `0.0583` to `0.007`
5. Retained the original, highest fracture rate for the elderly at `0.0583`

In general I tried to reduce the number of fractures and sprains, especially in adults age 19 - 65.

### Results:

| Injury | Population Living | Generated Prevalence* | Estimated Prevalence** | Actual Incidence | Source |
|:-------|:-----------------:|:---------------------:|:----------------------:|:----------------:|:-------|
| Concussions | 721 | 7.22% | 4.99% | 0.510% | [NIH](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2987636/) |
| Sprains | 1386 | 13.87% | 42.8% | 5.44% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Whiplash | 458 | 4.58% | 4.68% | 0.478% | [SRI](http://www.srisd.com/consumer_site/epidemiology.htm) |
| Spinal Trauma | 13 | 0.130% | 0.153% | 0.0153% | [NSCISC](https://www.nscisc.uab.edu/PublicDocuments/fact_figures_docs/Facts%202012%20Feb%20Final.pdf) |
| Gunshot Wounds | 23 | 0.230% | 0.418% | 0.0318% | [NIH](https://www.ncbi.nlm.nih.gov/pubmed/26116133) |
| Lacerations | 1293 | 12.94% | 23.2% | 2.61% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Fractures | 1504 | 15.1% | 45.2% | 5.83% | [BMUS](http://www.boneandjointburden.org/docs/By%20The%20Numbers%20-%20MSK%20Injuries.pdf) |
| Knee Injuries | 216 | 2.16% | 2.27% | 0.229% | [NIH](https://www.ncbi.nlm.nih.gov/pubmed/22506941) |
| Shoulder Injuries | 125 | 1.25% | 1.46% | 0.147% | [OJ](http://rheumatology.oxfordjournals.org/content/45/2/215.full) |
| Burns | 389 | 3.89% | 3.91% | 0.398% | [BF](http://www.burnfoundation.org/programs/resource.cfm?c=2&a=6) |

### Totals:

**Total Patients:** 13901  
**Deceased:** 3908  
**Living:** 9993


### *Generated Prevalence:

This is the percentage of **living** patients with this injury or disease (out of 9,993).

### **Estimating Prevalence:

I generated these patients with 10 years of history. Given the actual incidence, we can get an expected value for this 10-year period:

```
expected_value = P(injury)
expected_value = 1 - P(no_injury)
expected_value = 1 - ((1 - incidence) ^ num_years)
```

So, for example, if we had an injury with 5% incidence and we look at 10,000 patients over 10 years, we would expect to see:

```
expected_value = 1 - (1 - 0.05) ^ 10)

expected_value = 
    0.401
```

So we'd expect to see about 40% of the population with a history of that injury after 10 years, or about 4,000 people.

## A Typical Patient's Record

Here's a picture of 10 randomly selected patients out of the 100 I generated with logging turned on. In each column is the number of that type of injury the patient sustained during their lifetime. Note that some of these patients have not yet reached adulthood or old age.

### Full Life:

| Injury     | p0 | p1 | p2 | p3 | p4 | p5 | p6 | p7 | p8 | p9 | Avg. Per Patient |
|:-----------|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:----------------:|
| Concussion | **3** | 0 | 0 | **2** | 0 | **3** | **1** | 0 | 0 | **1** | 1.0 |
| Sprain     | **4** | **1** | **1** | **1** | 0| 0 | **1** | **1** | **1** | 9 | 1.0 |
| Whiplash   | 0 | 0 | 0 | **1** | **1** | 0 | 0 | 0 | 0 | 0 | 0.2 |
| Spinal     | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Gunshot    | 0 | **1** | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Laceration | 0 | **1** | **2** | **2** | 0 | **1** | **2** | **1** | **1** | **1** | 1.1 |
| Fracture   | 0 | **1** | **2** | **3** | **1** | 0 | **2** | **1** | **1** | **1** | 1.2 |
| Knee       | 0 | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0.1 |
| Shoulder   | 0 | 0 | **1** | 0 | **1** | 0 | 0 | 0 | 0 | 0 | 0.2 |
| Burn       | 0 | 0 | **1** | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0.2 |

### As Children:

| Injury     | p0 | p1 | p2 | p3 | p4 | p5 | p6 | p7 | p8 | p9 | Avg. Per Child |
|:-----------|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:----------------:|
| Concussion | **1** | 0 | 0 | **1** | 0 | **2** | 0 | 0 | 0 | 0 | 0.4 |
| Sprain     | **2** | **1** | 0 | **1** | 0 | 0 | 0 | 0 | **1** | 0 | 0.5 |
| Whiplash   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Spinal     | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Gunshot    | 0 | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0.1 |
| Laceration | 0 | 0 | **2** | **1** | 0 | **1** | 0 | 0 | **1** | 0 | 0.5 |
| Fracture   | 0 | **1** | **1** | 0 | 0 | 0 | **1** | **1** | **1** | **1** | 0.6 |
| Knee       | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Shoulder   | 0 | 0 | 0 | 0 | 0 | **1** | 0 | 0 | 0 | 0 | 0.1 |
| Burn       | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |


### As Elders:

| Injury     | p0 | p1 | p2 | p3 | p4 | p5 | p6 | p7 | p8 | p9 | Avg. Per Elder |
|:-----------|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:----------------:|
| Concussion | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0.1 |
| Sprain     | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0 | **1** | 0 | 0.2 |
| Whiplash   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Spinal     | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Gunshot    | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Laceration | 0 | 0 | 0 | **1** | 0 | 0 | 0 | 0 | 0 | 0 | 0.1 |
| Fracture   | 0 | 0 | 0 | **2** | **1** | 0 | **1** | 0 | 0 | 0 | 0.4 |
| Knee       | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Shoulder   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| Burn       | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

Overall I think this latest round of incidences was successful. Patients now seem fairly realistic.

**Pull request merged**
