### PR TITLE
New NDJSON files

### PR DESCRIPTION
**Pull request by jawalonoski**
Modifies FHIR bulk export to write NDJSON files for:

-  `Organization`
- `Location` (R4 only)
- `Practitioner`
- `PractitionerRole` (R4 only)

Addresses #1069

### CODE REVIEW

**Comment by IoTFier** [comment]
Hello @jawalonoski, how are you? 
Any thoughts on when this issue will be merged in the master ?

Thank you

**Comment by jawalonoski** [comment]
> Hello @jawalonoski, how are you? Any thoughts on when this issue will be merged in the master ?
> 
> Thank you

It is waiting for review. I also need time to look at https://github.com/synthetichealth/synthea/discussions/1107 and see if it is related or not.

**Comment by IoTFier** [comment]
Thank you, Jason.

**Comment by IoTFier** [comment]
Hi @eedrummer, how are you?
Any ETA on when will this change be ready for merge? I appreciate your help.
Thank you

**Comment by IoTFier** [comment]
/cc @jawalonoski 

Hi @eedrummer, how's it going? 
It will be great if this issue fix can be released to master branch sooner.
I will be very thankful to you. Will you please help?
Thank you

**Comment by eedrummer** [comment]
@IoTFier reviewing this PR now

**Comment by eedrummer** [comment]
@jawalonoski 

I'm getting a fairly repeatable test suite failure on my machine:

```
org.mitre.synthea.export.FHIRR4ExporterTest > testFHIRR4Export FAILED
    java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.hl7.fhir.r4.model.Identifier.getValue()" is null
        at org.mitre.synthea.export.FhirR4.findLocationUrl(FhirR4.java:882)
        at org.mitre.synthea.export.FhirR4.carePlan(FhirR4.java:2413)
        at org.mitre.synthea.export.FhirR4.convertToFHIR(FhirR4.java:314)
        at org.mitre.synthea.export.FhirR4.convertToFHIRJson(FhirR4.java:354)
        at org.mitre.synthea.export.FHIRR4ExporterTest.lambda$testFHIRR4Export$0(FHIRR4ExporterTest.java:114)
```

The key is `findLocationUrl` having an issue. I've seen the test fail this way, when exporting care plans, but it has also failed for me when exporting encounters.

Currently testing on:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```

I can run the test suite on `master` without any issues.

**Comment by IoTFier** [comment]
@jawalonoski  - thank you.
@eedrummer  - request to bring this forward to you attention. Also, any help on the build failure issue #1043 will also be appreciated. It is open for a while and there is no clue on why it keeps failing at the build. Consistent pattern is failure when  exporter.fhir.bulk_data = true.

**Comment by jawalonoski** [comment]
@eedrummer This last commit should fix the `java.lang.NullPointerException: Cannot invoke "String.equals(Object)"` issues you were seeing. I tested it with Java 8, 11, and 18 without issues.

**Comment by IoTFier** [comment]
Hi @eedrummer, thank you for the merge.
I will share my build results from my end with both option exporter.fhir.bulk_data = false and true.
Just a curiosity (from my experience so far) did you try the same on your end before merging?
Thank you

**Comment by IoTFier** [comment]
Build failed with exporter.fhir.bulk_data = true
image

image

**Comment by IoTFier** [comment]
@eedrummer 
Build also failed with exporter.fhir.bulk_data = false 

image

**Comment by IoTFier** [comment]
> @eedrummer This last commit should fix the `java.lang.NullPointerException: Cannot invoke "String.equals(Object)"` issues you were seeing. I tested it with Java 8, 11, and 18 without issues.

@jawalonoski - did it work for you with JDK 17.0.1?

**Comment by eedrummer** [comment]
@IoTFier - A few things:

* Setting `exporter.fhir.bulk_data` in `synthea.properties` *should* have no impact on running the test suite. Export related tests call [TestHelper.exportOff()](https://github.com/synthetichealth/synthea/blob/master/src/test/java/org/mitre/synthea/TestHelper.java#L98), which would disable that setting even if it were set to `true`. Regardless, I reran the test suite which worked for me on Java 17 with the value set to `true` and `false` just to double check.
* It looks like the first test suite failure you ran into hit some odd edge case in the simulation. I haven't seen an error like that in a while, as I thought we made some changes to deal with not a number results from value generators. If you can reproduce that failure, let us know. JSON export failures won't generate a file in the failed exports directory. If the code can't export JSON, then there isn't anything it is capable of outputting.
* We know that CCDA testing is flaky. We believe that this has to do with the MDHT library that is being used to validate the CCDAs. Our observation is that MDHT tends to be better behaved when running as a single test as opposed to a part of the whole test suite. I am currently working on rewriting the test so that it executes MDHT in a separate java process to see if that helps eliminate some of the flakiness.

**Comment by IoTFier** [comment]
@eedrummer - I upgraded my JDK to 17.0.4.1 as shown below; but build time getting an error. The java-home is pointing to the correct jdk location. Do I need to upgrade / update anything in the gradlew file?

java --version output
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

----------------------------------------------------
.\gradlew.bat build check test                  pwsh  13:50:10 

FAILURE: Build failed with an exception.

* What went wrong:
The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot\bin\java.exe

**Comment by IoTFier** [comment]
> @IoTFier - A few things:
> 
> * Setting `exporter.fhir.bulk_data` in `synthea.properties` _should_ have no impact on running the test suite. Export related tests call [TestHelper.exportOff()](https://github.com/synthetichealth/synthea/blob/master/src/test/java/org/mitre/synthea/TestHelper.java#L98), which would disable that setting even if it were set to `true`. Regardless, I reran the test suite which worked for me on Java 17 with the value set to `true` and `false` just to double check.
> * It looks like the first test suite failure you ran into hit some odd edge case in the simulation. I haven't seen an error like that in a while, as I thought we made some changes to deal with not a number results from value generators. If you can reproduce that failure, let us know. JSON export failures won't generate a file in the failed exports directory. If the code can't export JSON, then there isn't anything it is capable of outputting.
> * We know that CCDA testing is flaky. We believe that this has to do with the MDHT library that is being used to validate the CCDAs. Our observation is that MDHT tends to be better behaved when running as a single test as opposed to a part of the whole test suite. I am currently working on rewriting the test so that it executes MDHT in a separate java process to see if that helps eliminate some of the flakiness.

Will do. Question - In the first scenario - why did it not write the test sample in the exported failure folder?

**Comment by eedrummer** [comment]
@IoTFier The first test suite failure you posted had two failed tests. One was related to the JSON exporter. In this case, if the test fails, there will be no failed export file. 

The pipelines for exporting the different file formats are different. In some cases, it makes it easy to write out an export, even if difficulties are encountered.

CCDA falls into this camp. It's created using a template system that makes it really easy to write the results of the templates to a file. Failures are typically related as to whether the created information is valid, which happens after the initial file creation.

For JSON, the Synthea objects are passed into Gson, a library for reading and writing JSON. If this step fails, there isn't anything meaningful that can be written out.

The second failure was for `testUpdateAfterCreation`. This is a part of Synthea unrelated to export, so there is no related file.

I work using macOS.

**Comment by IoTFier** [comment]
Thank you @eedrummer. 
Looks like you and @jawalonoski are using Mac. Any possibility for either of you to run a build on win 11 pro 64 bit pc?

**Comment by IoTFier** [comment]
Build failed with exporter.fhir.bulk_data = false

.\gradlew.bat build check test                      pwsh  14:26:41 
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Task :test

org.mitre.synthea.export.JSONExporterTest > export FAILED
    java.lang.AssertionError: Validation of exported JSON bundle failed: Module Acute Myeloid Leukemia for PCOR Research Module does not have an entered time in exported module history
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.mitre.synthea.export.JSONExporterTest.export(JSONExporterTest.java:60)

531 tests completed, 1 failed, 6 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

**Comment by IoTFier** [comment]
Build failed with exporter.fhir.bulk_data = true

> Task :test

org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
    java.lang.AssertionError: Validation of exported CCDA failed: Illegal operation (self.realmCode->isEmpty()) expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.mitre.synthea.export.CCDAExporterTest.testCCDAExport(CCDAExporterTest.java:71)

531 tests completed, 1 failed, 6 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

**Pull request merged**
