### PR TITLE
Ruby v2.4 support for #199 and #200.

### PR DESCRIPTION
**Pull request by preston**

### CODE REVIEW

**Comment by preston** [comment]
CC @jawalonoski

**Comment by jawalonoski** [comment]
So, it doesn't look like your fork of health data standards is building correctly, based on this PR: https://github.com/projectcypress/health-data-standards/pull/501

Can you verify?

**Comment by preston** [comment]
@jawalonoski The travis logs show everything is actually passing. It appears to be rubocop style errors that are causing the build to fail.

**Comment by preston** [comment]
Will recreate this to update the example mongoid config file using the correct v5 structure.

**Pull request closed without merging**
