### PR TITLE
WIP: Fix decimal points on vitals to be realistic

### PR DESCRIPTION
**Pull request by shabiel**
First attempt at #555, and my first Java code in a few years...

This PR doesn't just address Blood Pressures, it also addresses Height, Weight, BMI. It's very preliminary to see if this is the way I should go about changing things.

I didn't address pain yet as I couldn't figure out how to identify an observation is a Pain observation.

The FHIR R4 output generated by this comes out good for BP, Ht, Wt, BMI. BP are exported as Integers/Long, Ht, Wt, BMI as Big Decimals with 1 or 2 decimal points.

### CODE REVIEW

**Comment by jawalonoski** [comment]
I'm not sure why the Travis build failed, so I'm going to restart it.

@shabiel, please make sure you eventually address the checkStyle complaints when you are ready.

You can ignore the missing Javadoc messages like:
```
Missing a Javadoc comment. [JavadocMethod]
```
But these type of warnings should be addressed... attempting to keep the style relatively consistent.
```
Line is longer than 100 characters (found 103). [LineLength]
WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
WhitespaceAround: '{' is not preceded with whitespace. [WhitespaceAround]
'vitalSign' has incorrect indentation level 10, expected level should be 12. [Indentation]
'}' at column 9 should be on the same line as the next part of a multi-block statement (one that directly contains multiple blocks: if/else-if/else, do/while or try/catch/finally). [RightCurlySame]
'if' construct must use '{}'s. [NeedBraces]
'method def modifier' has incorrect identation level 0, expected level should be 2. [Indentation]
Line contains a tab character. [FileTabCharacter]
'||' should be on a new line. [OperatorWrap]
```

**Comment by shabiel** [comment]
I didn't know about the style check (I just saw it this morning as
well in the Travis build). I will address them. Thank you.

When you ready, can you let me know if you think my approach is
reasonable? The code is kinda messy and there are dead paths right now
(which I found after I pushed it yesterday); but I wanted to know if
this looks like a good direction.

--Sam

**Comment by jawalonoski** [comment]
It looks like StateTest is the culprit... should `120L` (as a Long) and not `120` (Integer) for some reason.

**Comment by shabiel** [comment]
Yes. Math.round(double) returns Long. And HAPI FHIR classes include a
Quantity constructor that takes Long, so in the end I kept Blood
Pressures as Long. I tried to cast it to Integer but the code didn't
compile (because of a warning on loss of precision)--and I was running
out of time... should have fixed it if I had know that it will affect
Travis.

**Comment by jawalonoski** [comment]
👍 Thank you for this inspiring PR, but it is now overcome by events now with #573.

**Pull request closed without merging**
