### PR TITLE
Performance optimization for FHIR bulk export 

### PR DESCRIPTION
**Pull request by eugene-blokhin**
This PR contains a performance optimization for `*.ndjson` generation.

Execution times for `./run_synthea -p 10000`:
* with this fix: **16:32**
* without fix:  **34:31**

The tests have been performed on a MacBook Pro with specs:
```
16 GB 1600 MHz DDR3
2.2 GHz Quad-Core Intel Core i7
```

### CODE REVIEW

**Comment by jawalonoski** [comment]
Thank you for the pull request. I tested it and it seems like a nice enhancement.

Couple of thoughts:

- If you call `Exporter.closeOpenFiles()` once at the very end of `Exporter.runPostCompletionExports(...)`, you do not need to modify `App.java` or `Generator.java` whatsoever.
- Your edits create several checkstyle warnings. Can you correct them, please?

```
> Task :checkstyleMain
[ant:checkstyle] [WARN] Exporter.java:9: Wrong lexicographical order for 'java.io.IOException' import. Should be before 'java.io.PrintWriter'. [CustomImportOrder]
[ant:checkstyle] [WARN] Exporter.java:53: Line is longer than 100 characters (found 117). [LineLength]
[ant:checkstyle] [WARN] Exporter.java:54:46: WhitespaceAround: '*' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:54:47: WhitespaceAround: '*' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:54:51: WhitespaceAround: '*' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:54:52: WhitespaceAround: '*' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:346:19: WhitespaceAround: 'synchronized' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:350: Line is longer than 100 characters (found 110). [LineLength]
[ant:checkstyle] [WARN] Exporter.java:359:17: WhitespaceAround: 'synchronized' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:369:10: WhitespaceAround: 'while' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:369:25: WhitespaceAround: '{' is not preceded with whitespace. [WhitespaceAround]
[ant:checkstyle] [WARN] Exporter.java:369:30: Line contains a tab character. [FileTabCharacter]
Checkstyle rule violations were found. See the report at: synthea/build/reports/checkstyle/main.html
Checkstyle files with violations: 1
Checkstyle violations by severity: [warning:12]
```

**Comment by eugene-blokhin** [comment]
Thanks for the quick reaction and the suggestion about `Exporter.runPostCompletionExports(...)`. I was having a hard time finding an elegant way to close the files.

I pushed the update with the applied review notes.

**Comment by jawalonoski** [comment]
Looks like all the unit tests passed, but the slack notification failed. So I'm not worried about the ❌ icons above.

**Comment by jawalonoski** [comment]
@eugene-blokhin thank you for the pull request!

**Pull request merged**
