### PR TITLE
Fix utility tasks so they work when run from a jar file

### LINKED ISSUE #960: retrieving concepts listing using release jar
I'm attempting to retrieve the listing of concepts in running modules (which works using ./gradlew concepts) however when attempting to do so using the released jar I get the following error:

ava -cp synthea-with-dependencies.jar org.mitre.synthea.helpers.Concepts false
Performing an inventory of concepts...
Exception in thread "main" java.nio.file.FileSystemNotFoundException
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
        at java.nio.file.Paths.get(Paths.java:143)
        at org.mitre.synthea.helpers.Utilities.walkAllModules(Utilities.java:435)
        at org.mitre.synthea.helpers.Concepts.getConceptInventory(Concepts.java:73)
        at org.mitre.synthea.helpers.Concepts.main(Concepts.java:49)

Is there a way to perform the inventory on the release jar?

### PR DESCRIPTION
**Pull request by hadleynet**
Closes #960

### CODE REVIEW

**Comment by dehall** [comment]
Confirmed this fixes the issue and doesn't appear to break anything on Mac or Windows, via gradlew or via an uberJar. Any reason we shouldn't update the other tasks with the same fix while we're at it? Specifically I'm thinking of the Attributes and Graphviz tasks.

**Comment by hadleynet** [comment]
No reason not to update the other tasks while we are at it. I can take a look Tue or Wed.

**Comment by dehall** [comment]
For some reason the Graphviz output doesn't work when run from a JAR on Windows. The images don't show up anywhere that I can find. It works fine when running from gradle though. Every other combination appears to be fine.
Seems like it's trying to write to a bad filepath: (I added an extra log line here to try to debug)

via gradle:
```
PS C:\Users\Dylan\synthea> .\gradlew.bat graphviz

> Task :graphviz
Scanned 67 modules and 75 submodules.
Rendering graphs to `C:\Users\Dylan\synthea\.\output\graphviz`...
Loading C:\Users\Dylan\synthea\build\resources\main\modules\allergic_rhinitis.json
Trying to write to .\output\graphviz\allergic_rhinitis.png
Loading C:\Users\Dylan\synthea\build\resources\main\modules\allergies\allergy_panel.json
Trying to write to .\output\graphviz\allergies\allergy_panel.png
...
```

via jar:
```
PS C:\Users\Dylan\synthea> java -cp .\build\libs\synthea-with-dependencies.jar Graphviz
Scanned 67 modules and 75 submodules.
Rendering graphs to `C:\Users\Dylan\synthea\.\output\graphviz`...
Loading /modules/wellness_encounters.json
Trying to write to \modules\wellness_encounters.png
Loading /modules/weight_loss/mend_week.json
Trying to write to \modules\weight_loss\mend_week.png
...
```

Honestly it's not a big deal if that one is broken (there's not much point to running graphviz from the jar since we do publish all the default module graphs anyway, and the module builder is even better), but I do want to poke at it just a little more to try to figure that out

**Review by dehall — APPROVED** [review]
Confirmed on Mac and Windows

**Pull request merged**
