### PR TITLE
WIP: Expressions using CQL Engine

### PR DESCRIPTION
**Pull request by dehall**
For discussion:
Implements a simple "expressions" concept (#189) using a CQL engine. SetAttribute, Observations, and VitalSigns now include an "expression" field which gets translated and passed to a CQL engine for evaluation.  The details of the implementation are all abstracted away in a new ExpressionProcessor class. The translation layer allows for selected attributes, identified with a ruby-esque "#{attr}", on the patient to be referenced and added to the evaluation context.

For example, the expression "#{age} / 2 + 7" for a patient with the attribute "age" defined as 26 will result in the following CQL being evaluated:

```
library Synthea version '1'

context Patient


define age: 26
define result: age / 2 + 7
```

My goal here was to enable the kind of basic calculations that are used in the current Java modules, without forcing module writers to care about the details and boilerplate of CQL.

Some open questions:
1. Do we want to allow more complex logic, perhaps allowing people to write raw/multiline CQL to be passed directly to the engine?
2. How should we support referencing vital signs? I do like keeping vital signs separate from attributes, but at the same time if we can define arbitrary vital signs there isn't much distinguishing them and it may be easier to just merge vital signs back into attributes.
3. How should we support referencing the current time? (Ex. to reproduce the current smoking logic which uses a linear formula based on the current year) Do we want to add any convenience items or leverage the existing CQL date operators?
4. Is this missing anything else?

### CODE REVIEW

**Comment by nanowizard** [comment]
Reviving this thread as mathematical expressions for vital sign / attribute assignment will be a necessity for physiology submodule support that I'm working on. I expect models will frequently provide parameters which do not line up specifically with Synthea's set of vital signs, but which are mathematically related.

For example, the initial model I'm working with is a circulatory haemodynamics model which provides left ventricle volume (V_lv). In order to match that up with our Left Ventricular Ejection Fraction (LVEF) vital sign, we'll need an expression of the form "LVEF = max(V_lv) - min(V_lv)".

I suspect we could easily run into situations where more complex mathematical expressions involving square roots, exponentials, trig functions, logarithms, etc. are required. Looking through the repositories it's unclear to me if CQL supports these functions. Some alternative libraries which may provide mathematical expression functionality more specifically are [mXparser](http://mathparser.org/) or [EvalEx](https://github.com/uklimaschewski/EvalEx).

If CQL supports the functions mentioned above and can support sufficiently powerful expressive capability then I'm all for using that. But if not then I'd recommend going with something more math expression specific.

Thoughts?

**Comment by cmoesel** [comment]
CQL supports many mathematical operations.  Check out the following to parts of the reference section in the CQL spec:
https://cql.hl7.org/09-b-cqlreference.html#arithmetic-operators-4
https://cql.hl7.org/09-b-cqlreference.html#aggregate-functions

Do those sets of capabilities seem robust enough for what you'd need?

**Comment by cmoesel** [comment]
One other thing I'll add is regarding the approach of generating a CQL file w/ the pertinent data hard-coded.  The description uses this example:

```
library Synthea version '1'

context Patient

define age: 26
define result: age / 2 + 7
```

This approach requires CQL-to-ELM to recompile every CQL snippet for every Synthea patient.  CQL-to-ELM compilation is fairly fast, but I wouldn't say it's cheap.  It would be more efficient if you could write the CQL snippet with `parameter`s for the variable data.  Then you only need to run CQL-to-ELM once and you pass in the `parameter` values when you execute it for each patient.  Using this approach, your example might look like this:

```
library Synthea version '1'

parameter PatientAge Integer

context Patient

define result: PatientAge / 2 + 7
```

The other approach, which is more complicated but also more robust, would be to use CQL retrieves to get the current Synthea patient's data for calculation -- but then you'd need to implement a data source to work w/ the Synthea data.  If you did that, though, you could use something like CQL's `AgeInYears` operator to automatically get the patient's age.  But... for now, the more reasonable approach is probably `parameter`s.

**Comment by nanowizard** [comment]
Thank you @cmoesel! This is all great info and it seems like CQL should give us everything we need. I'll start working that into my physiology branch and let you know if I run into any hiccups.

**Pull request merged**
