### PR TITLE
Fixes for duplicate entry bugs in FHIR R4 exporter

### LINKED ISSUE #795: FHIR Export Duplication Data and Transactions
See this thread: https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Synthea/near/210288132

Summary of requested change:

- When transaction bundles, organization, and practitioner FHIR exports are enabled (or create a separate explicit configuration parameter):
    - Do not duplicate Organizations and Practitioners in each Patient bundle.
- Change transaction POSTs to be [conditional creates](https://www.hl7.org/fhir/http.html#ccreate) using the `ifNoneExist` parameter
- Add an option for conditional references (see https://www.hl7.org/fhir/http.html#trules)

### LINKED ISSUE #797: FHIR Location Duplicates
See https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Synthea.20data.20issue.3A.20duplicate.20identical.20Locations.3F

### PR DESCRIPTION
**Pull request by hadleynet**
Closes #795 and #797.

### CODE REVIEW

**Comment by hadleynet** [comment]
Note that this pull request currently only addresses FHIR R4 exporter changes. The same approach is applicable to DSTU2 and STU3 but looking for feedback before tackling those.

**Comment by hadleynet** [comment]
I've added a wiki page that explains how to use transaction bundles: https://github.com/synthetichealth/synthea/wiki/FHIR-Transaction-Bundles

I'll link it from the TOC once this PR is merged.

**Comment by timharsch** [comment]
Coming from the point of view of someone who is looking to use synthea to create patient populations:  I work on software that pulls EHR info.  Unfortunately, DSTU2 and STU3 aren't well supported by providers at this time (some fairly convincing evidence of this is to use the Lantern dashboard at https://lantern.healthit.gov/?tab=endpoints_tab , and filter by FHIR version using the pull down .. you'll see that out of >1500 endpoints only one is classified as STU3 and only one is R4).
So, for those of us looking to duplicate real world conditions, only DSTU2 matters.

**Comment by hadleynet** [comment]
The fixes we made to remove duplicate resources were also made to the the STU3 and DSTU2 exporters. Please let us know if you find any issues.

**Pull request merged**
